### ISSUE TITLE
“The application bundle does not contain a valid identifier” error after installing socket mobile scan api sdk

### ISSUE THREAD

**Issue by monkaung** [SocketMobile/singleentryswift-ios#1]
Pleas check detail on SO : http://stackoverflow.com/questions/39114047/the-application-bundle-does-not-contain-a-valid-identifier-error-after-install

**Comment by zeshanmusawar** [comment]
I solve this problem after I delete all build files by Xcode. Your build file path at Xcode > Preferences > Locations > Derived Data
