### ISSUE TITLE
No podspec found for `ScanAPI` in `../ScanApiSDK-10.3.90`

### ISSUE THREAD

**Issue by kbabulrao** [SocketMobile/singleentryswift-ios#5]
I am getting No podspec found for `ScanAPI` in `../ScanApiSDK-10.3.90`  when i am trying to update the CocoaPods. Could you please guide me.

<img width="567" alt="screen shot 2017-09-04 at 6 56 32 pm" src="https://user-images.githubusercontent.com/5792888/30028581-42f01ddc-91a3-11e7-8ba8-d8f1281b293d.png">

**Comment by Eric-Glaenzer** [comment]
Did you unzip the ScanApiSDK as explained in the Readme.md?

**Comment by kbabulrao** [comment]
No, to download the ScanApiSDK. "Socket Mobile Subscription" is mandatory?

I downloaded the singleentryswift-ios sample  and i am trying to update the cocoapods.

I unable to open PodFile as well. Because it is showing as below. 

<img width="248" alt="screen shot 2017-09-05 at 5 31 21 pm" src="https://user-images.githubusercontent.com/5792888/30060276-3fc72552-9260-11e7-9546-1992cd3b9493.png">

**Comment by EricGlaenzer** [comment]
Yes that's correct, you need a Socket Mobile Subscription in order to download the ScanApi SDK.

**Comment by kbabulrao** [comment]
Thank you for clarifying. I'll go with Socket Mobile Subscription.
