### ISSUE TITLE
Where can we download the 10.3.93 (or later) version?! 

### ISSUE THREAD

**Issue by rvlieshout** [SocketMobile/singleentryswift-ios#7]
The developers portal offers 10.3.90.

**Comment by LenOttSocketMobile** [comment]
Rvlieshout, Our apologies, the update was posted a few days ago, but I think it got 'lost' due to some system work the MarCom team was doing.  Please check back later today (Tuesday), I have contacted our MarCom team and should be back later today.
Regards, 
Len

**Comment by LenOttSocketMobile** [comment]
Ok, all updated.  You should be able to download .93!
Sorry for the delay!
