### ISSUE TITLE
swift 4.0 support of SCANAPI SDK 

### ISSUE THREAD

**Issue by chetandobariya** [SocketMobile/singleentryswift-ios#8]
Hello there,

Do you have any demo project using SCANAPI SDK which is supporting latest swift syntax 4.0?

Thanks,
Chetan

**Comment by EricGlaenzer** [comment]
Hello Chetan,
We are in the process of releasing a new SDK called Capture which will replace ScanAPI. I invite you to check it out on our developer portal. This new SDK follows the same principle as ScanAPI with some improvements.
