### ISSUE TITLE
Undefined symbols for architecture x86_64/arm

### ISSUE THREAD

**Issue by schnabler** [SocketMobile/singleentryswift-ios#9]
Hey,

I'm using Cocoapods v1.3.1 (`use_frameworks!` option) to integrate the latest ScanApiSDK into my project using XCode 9 and Swift4. I have been getting the following error randomly for a while. Sometimes cleaning the project and/or the build folder will get rid of it, sometimes I have to do this multiple times, someting opening/closing XCode works.

This is the error message when trying to build for the simulator, when building for a real device, the compiler gives me the same error for arm. What do I do to fix this? Thanks.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DeviceInfo", referenced from:
      objc-class-ref in SocketMobileController.o
  "_OBJC_CLASS_$_ScanApiHelper", referenced from:
      objc-class-ref in SocketMobileController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by EricGlaenzer** [comment]
Hi shnaber, 
I will look into this and report here my findings. Did you always use CocoaPods to integrate our SDK in your app? I am asking this because our previous releases of the SDK without using CocoaPods set some path to our libraries that might not have been cleared when switching to a cocoapods installation.

**Comment by EricGlaenzer** [comment]
I am closing this issue since shnaber did not reply to my last question. I would also recommend using our latest Capture SDK, which is available now from the official CocoaPods.org repository.
